trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  sourceDirectory: '$(Build.SourcesDirectory)/'

steps:
- script: |
    sqllocaldb create MSSQLLocalDB
    sqllocaldb start MSSQLLocalDB
    sqllocaldb info MSSQLLocalDB

    C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe start
  displayName: Start instance of LocalDB